### ISSUE TITLE
关于modules.py这一文件中的问题

### ISSUE THREAD

**Issue by yujh123** [LeeSureman/Batch_Parallel_LatticeLSTM#11]
您好，我想问一下，
1.在mosules.py这个文件中，关于MultiInputLSTMCell这个类的forward函数中，skip_mask是指的什么？
2.在这个forward函数中做了什么操作呢？
3.与原代码相比是有做什么优化吗？

**Comment by LeeSureman** [comment]
原代码不能batch并行

**Comment by yujh123** [comment]
> 原代码不能batch并行

您好，我能请教一下您如果我想把LSTM结构改成GRU的话需要改哪些地方吗？我自己改了好久，总是报错。。。也不知道改的对不对。。

**Comment by LeeSureman** [comment]
需要改两处，一个是word cell，一个是multi input cell，感觉没什么改的必要啊。。

**Comment by yujh123** [comment]
> 需要改两处，一个是word cell，一个是multi input cell，感觉没什么改的必要啊。。

嗐，就是想改进一下代码嘛，作为一个论文里的创新点那样。。但是感觉改起来好麻烦，一会维度不对了一会又哪里报错啥的。。。

**Comment by LeeSureman** [comment]
啥论文？如果要投顶会的话，这种创新就忽略不计了。 是挺麻烦的，主要还是维度吧，唉我现在没空把代码注释一下了，各种控制mask的部分是挺复杂的【捂脸】

**Comment by yujh123** [comment]
> 啥论文？如果要投顶会的话，这种创新就忽略不计了。 是挺麻烦的，主要还是维度吧，唉我现在没空把代码注释一下了，各种控制mask的部分是挺复杂的【捂脸】

我们不用投会议。。就是想着算毕业论文里面的一个创新点。。。我感觉这个弄出来也不怎么好啊但是我们老师就坚持让我把这个弄出来，说是这个就可以作为一个创新点，我也没办法，就硬着头皮弄。。但是自己又太渣了，不会弄。。。。

**Comment by LeeSureman** [comment]
【捂脸】没想到我这个破代码还能和那么重要的事扯上关系。。

**Comment by yujh123** [comment]
> 【捂脸】没想到我这个破代码还能和那么重要的事扯上关系。。



> 【捂脸】没想到我这个破代码还能和那么重要的事扯上关系。。

大佬别这么说，假如我也跟你一样那么强的话就不用愁了。

**Comment by LeeSureman** [comment]
关于形状错误的话，你就把变量的形状输出一下就好了。另外也可以去看原版代码的forward

**Comment by yujh123** [comment]
> 关于形状错误的话，你就把变量的形状输出一下就好了。另外也可以去看原版代码的forward

行，我再改一下，参数什么的还能设置一下，主要是类似skip_word_flat skip_source_flat这种变量名不知道是什么意思，不太懂具体流程。。。

**Comment by LeeSureman** [comment]
pytorch中取index，只能用一维的list去取，所以需要将它们展开来，取完后再还原为batch

**Comment by yujh123** [comment]
> pytorch中取index，只能用一维的list去取，所以需要将它们展开来，取完后再还原为batch

行，我再研究一下，不懂得可能还要叨扰您了~谢谢您的答复~
