### ISSUE TITLE
您好！请教实验中的一点细节？

### ISSUE THREAD

**Issue by topDreamer** [LeeSureman/Batch_Parallel_LatticeLSTM#18]
![image](https://user-images.githubusercontent.com/29766163/83484155-d4e5ad80-a4d6-11ea-8d82-f6f4d286f300.png)
您好！第一个问题是：对于实验中的截图1所示，char+bichar的实验是怎么拼接的呢？比如“南京市长江大桥”其中的“南”后面直接拼接bichar“南京”吗？然后“京”后拼接“京市”？依次这样吗...这样最后一个字“桥”拼接的bichar是自身？
另外一个问题：截图2所示，这里面的word和char是在embedding层就直接拼接的吗？请教下如何拼接的，感谢回复！

**Comment by LeeSureman** [comment]
是的，你说的没错，这里桥的bichar可以理解为是桥+<end>

**Comment by topDreamer** [comment]
感谢李博士的回复！第二个问题是实验中不使用LatticeLSTM，这里面的对照实验

**Comment by topDreamer** [comment]
感谢李博士的回复！第二个问题是实验中不使用LatticeLSTM，如上截图红框2这里面的对照实验wordbaseline+char请教下如何拼接的，感谢回复！

**Comment by LeeSureman** [comment]
那个情况下输入的每个token是词，char LSTM指的是用LSTM在字的粒度上为每个词形成一个表示，比如说一个token是 东方明珠，那么它的表示由两个embedding拼接得到，1.东方明珠的词embedding 2.[东, 方, 明, 珠] 过LSTM形成的表示，具体在 原文的3.2节有

**Comment by topDreamer** [comment]
明白了，谢谢李博士🙏
