### ISSUE TITLE
请问在main.py文件的哪里加文件路径啊

### ISSUE THREAD

**Issue by yujh123** [LeeSureman/Batch_Parallel_LatticeLSTM#4]
您好，您说在main.py中添加三个embedding的文件路径以及对应数据集的路径即可运行，具体是哪个地方呢？

**Comment by LeeSureman** [comment]
yangjie_rich_pretrain_unigram_path
yangjie_rich_pretrain_bigram_path
yangjie_rich_pretrain_word_path
以上三个变量以及你需要运行的数据集路径

**Comment by yujh123** [comment]
> yangjie_rich_pretrain_unigram_path
> yangjie_rich_pretrain_bigram_path
> yangjie_rich_pretrain_word_path
> 以上三个变量以及你需要运行的数据集路径

谢谢您的回复，但是三个embedding文件不是数据集嘛。。。

**Comment by LeeSureman** [comment]
就是把这三个变量和需要跑的数据集路径设置为对应的在你本机上的文件路径

**Comment by yujh123** [comment]
> 就是把这三个变量和需要跑的数据集路径设置为对应的在你本机上的文件路径

那我想用Resume数据集，是从原作者的data文件里下载嘛？

**Comment by LeeSureman** [comment]
是的，包括三个embedding文件的下载链接也在他仓库的readme里有

**Comment by yujh123** [comment]
好的 谢谢您 我再运行一下试试

**Comment by yujh123** [comment]
> 是的，包括三个embedding文件的下载链接也在他仓库的readme里有



想问一下您的fitlog怎么设置的，之前我没有用过这个包 会报错。。。。报错内容如下：




Folder depth out of limitation.  File "E:/论文/问答系统/Lattice LSTM/Batch_Parallel_LatticeLSTM/main.py", line 53, in <module>

    fitlog.commit(__file__,fit_msg=fit_msg)
Can not find the config file.
  File "C:\Users\yjh\Anaconda3\lib\site-packages\fitlog\__init__.py", line 65, in commit
    _logger.commit(file, fit_msg)
  File "C:\Users\yjh\Anaconda3\lib\site-packages\fitlog\fastlog\logger.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\yjh\Anaconda3\lib\site-packages\fitlog\fastlog\logger.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\yjh\Anaconda3\lib\site-packages\fitlog\fastlog\logger.py", line 117, in commit
    raise RuntimeError("It seems like you are not running under a folder governed by fitlog.\n" + msg['msg'])
RuntimeError: It seems like you are not running under a folder governed by fitlog.
Error: Config file is not found

**Comment by tyistyler** [comment]
楼主和作者您好，作为小白，我还是没明白在哪里添加路径，三个数据集要怎么传进去呢，另外我只找到了两个embedding文件，，

**Comment by LeeSureman** [comment]
你找到哪两个embedding文件

**Comment by tyistyler** [comment]
gigaword_chn.all.a2b.uni.ite50.vec
ctb.50d.vec
这两个

**Comment by tyistyler** [comment]
from pathes import *
//ontonote4ner_cn_path = 0
yangjie_rich_pretrain_unigram_path = ‘gigaword_chn.all.a2b.uni.ite50.vec’
yangjie_rich_pretrain_bigram_path = ctb.50d.vec‘’
resume_ner_path = ‘.data/resume’#里面有train、dev、test
//weibo_ner_path = 0
我是这么写的

**Comment by LeeSureman** [comment]
还缺个bigram的，https://pan.baidu.com/s/1pLO6T9D#list/path=%2F，里面有

**Comment by LeeSureman** [comment]
ctb.50d.vec我记得是lexicon的向量

**Comment by tyistyler** [comment]
yangjie_rich_pretrain_unigram_path = ‘gigaword_chn.all.a2b.uni.ite50.vec’
yangjie_rich_pretrain_bigram_path = 'bigram...’
yangjie_rich_pretrain_word_path=‘ctb.50d.vec’
resume_ner_path = ‘.data/resume’#里面有train、dev、test
请问数据集可以这样导入么？
十分感谢您的回答

**Comment by LeeSureman** [comment]
可以的

**Comment by tyistyler** [comment]
谢谢

**Comment by tyistyler** [comment]
请问运行时出现这个问题，但是代码load_data.py中已经注释掉了
，该怎么解决呀？
FileNotFoundError:/remote-home/xnli/data/corpus/swquence_labelling/chinese_ner/WeiboNER

**Comment by LeeSureman** [comment]
你没改路径或没改用哪个dataset吧

**Comment by tyistyler** [comment]
weibo_ner_path = ‘.data/WeiboNER’//train.all.bmes、dev.all.bmes、test.all.bmes
我用的是这个路径，还需要修改load_data.py里的内容么

**Comment by LeeSureman** [comment]
应该就好了呀

**Comment by LeeSureman** [comment]
你看看你改的路径有没有被传到load_weibo_ner里去

**Comment by tyistyler** [comment]
感谢大佬，路径没传进去，我在pathes.py中重新修改的

**Comment by LeeSureman** [comment]
好的，恭喜

**Comment by 2151330** [comment]
您好，bigram的获取链接失效了，可以在分享一下吗
