### ISSUE TITLE
怎么进行inference

### ISSUE THREAD

**Issue by 18222278799** [LeeSureman/Batch_Parallel_LatticeLSTM#9]
您好，怎么用这个进行inference，fastnlp倒是有一个predictor函数，但是输入是一个dataset，是不是重新构建一个dataset很麻烦，您是怎么进行推断的呢

**Comment by zhangtianlin** [comment]
好难写

**Comment by zhangtianlin** [comment]
写好了

**Comment by LeeSureman** [comment]
抱歉回的晚了，恭喜已经写好，由于用了fitlog记录结果，我自己也没有inference的需求，就没写了，抱歉。

**Comment by MrRace** [comment]
> 写好了
@zhangtianlin
求下 inference的代码~
